const provinces = [
    {
        id:73,
        name:"ABRA",
        regCode:"14",
        provCode:"1401"
    },
    {
        id:84,
        name:"AGUSAN DEL NORTE",
        regCode:"16",
        provCode:"1602"
    },
    {
        id:85,
        name:"AGUSAN DEL SUR",
        regCode:"16",
        provCode:"1603"
    },
    {
        id:33,
        name:"AKLAN",
        regCode:"06",
        provCode:"0604"
    },
    {
        id:78,
        name:"APAYAO",
        regCode:"14",
        provCode:"1481"
    },
    {
        id:34,
        name:"ANTIQUE",
        regCode:"06",
        provCode:"0606"
    },
    {
        id:16,
        name:"AURORA",
        regCode:"03",
        provCode:"0377"
    },
    {
        id:79,
        name:"BASILAN",
        regCode:"15",
        provCode:"1507"
    },
    {
        id:10,
        name:"BATAAN",
        regCode:"03",
        provCode:"0308"
    },
    {
        id:17,
        name:"BATANGAS",
        regCode:"04",
        provCode:"0410"
    },
    {
        id:5,
        name:"BATANES",
        regCode:"02",
        provCode:"0209"
    },
    {
        id:74,
        name:"BENGUET",
        regCode:"14",
        provCode:"1411"
    },
    {
        id:48,
        name:"BILIRAN",
        regCode:"08",
        provCode:"0878"
    },
    {
        id:39,
        name:"BOHOL",
        regCode:"07",
        provCode:"0712"
    },
    {
        id:49,
        name:"BUKIDNON",
        regCode:"10",
        provCode:"1013"
    },
    {
        id:11,
        name:"BULACAN",
        regCode:"03",
        provCode:"0314"
    },
    {
        id:6,
        name:"CAGAYAN",
        regCode:"02",
        provCode:"0215"
    },
    {
        id:28,
        name:"CAMARINES NORTE",
        regCode:"05",
        provCode:"0516"
    },
    {
        id:29,
        name:"CAMARINES SUR",
        regCode:"05",
        provCode:"0517"
    },
    {
        id:54,
        name:"CAMIGUIN",
        regCode:"10",
        provCode:"1018"
    },
    {
        id:35,
        name:"CAPIZ",
        regCode:"06",
        provCode:"0619"
    },
    {
        id:30,
        name:"CATANDUANES",
        regCode:"05",
        provCode:"0520"
    },
    {
        id:40,
        name:"CEBU",
        regCode:"07",
        provCode:"0722"
    },
    {
        id:52,
        name:"CITY OF ISABELA",
        regCode:"09",
        provCode:"0997"
    },
    {
        id:67,
        name:"COTABATO CITY",
        regCode:"12",
        provCode:"1298"
    },
    {
        id:63,
        name:"COTABATO (NORTH COTABATO)",
        regCode:"12",
        provCode:"1247"
    },
    {
        id:61,
        name:"COMPOSTELA VALLEY",
        regCode:"11",
        provCode:"1182"
    },
    {
        id:58,
        name:"DAVAO DEL NORTE",
        regCode:"11",
        provCode:"1123"
    },
    {
        id:59,
        name:"DAVAO DEL SUR",
        regCode:"11",
        provCode:"1124"
    },
    {
        id:60,
        name:"DAVAO ORIENTAL",
        regCode:"11",
        provCode:"1125"
    },
    {
        id:62,
        name:"DAVAO OCCIDENTAL",
        regCode:"11",
        provCode:"1186"
    },
    {
        id:88,
        name:"DINAGAT ISLANDS",
        regCode:"16",
        provCode:"1685"
    },
    {
        id:43,
        name:"EASTERN SAMAR",
        regCode:"08",
        provCode:"0826"
    },
    {
        id:75,
        name:"IFUGAO",
        regCode:"14",
        provCode:"1427"
    },
    {
        id:36,
        name:"ILOILO",
        regCode:"06",
        provCode:"0630"
    },
    {
        id:1,
        name:"ILOCOS NORTE",
        regCode:"01",
        provCode:"0128"
    },
    {
        id:2,
        name:"ILOCOS SUR",
        regCode:"01",
        provCode:"0129"
    },
    {
        id:7,
        name:"ISABELA",
        regCode:"02",
        provCode:"0231"
    },
    {
        id:76,
        name:"KALINGA",
        regCode:"14",
        provCode:"1432"
    },
    {
        id:19,
        name:"LAGUNA",
        regCode:"04",
        provCode:"0434"
    },
    {
        id:55,
        name:"LANAO DEL NORTE",
        regCode:"10",
        provCode:"1035"
    },
    {
        id:80,
        name:"LANAO DEL SUR",
        regCode:"15",
        provCode:"1536"
    },
    {
        id:3,
        name:"LA UNION",
        regCode:"01",
        provCode:"0133"
    },
    {
        id:44,
        name:"LEYTE",
        regCode:"08",
        provCode:"0837"
    },
    {
        id:81,
        name:"MAGUINDANAO",
        regCode:"15",
        provCode:"1538"
    },
    {
        id:22,
        name:"MARINDUQUE",
        regCode:"17",
        provCode:"1740"
    },
    {
        id:31,
        name:"MASBATE",
        regCode:"05",
        provCode:"0541"
    },
    {
        id:12,
        name:"NUEVA ECIJA",
        regCode:"03",
        provCode:"0349"
    },
    {
        id:8,
        name:"NUEVA VIZCAYA",
        regCode:"02",
        provCode:"0250"
    },
    {
        id:68,
        name:"NCR, CITY OF MANILA, FIRST DISTRICT",
        regCode:"13",
        provCode:"1339"
    },
    {
        id:69,
        name:"CITY OF MANILA",
        regCode:"13",
        provCode:"1339"
    },
    {
        id:70,
        name:"NCR, SECOND DISTRICT",
        regCode:"13",
        provCode:"1374"
    },
    {
        id:71,
        name:"NCR, THIRD DISTRICT",
        regCode:"13",
        provCode:"1375"
    },
    {
        id:72,
        name:"NCR, FOURTH DISTRICT",
        regCode:"13",
        provCode:"1376"
    },
    {
        id:37,
        name:"NEGROS OCCIDENTAL",
        regCode:"06",
        provCode:"0645"
    },
    {
        id:41,
        name:"NEGROS ORIENTAL",
        regCode:"07",
        provCode:"0746"
    },
    {
        id:45,
        name:"NORTHERN SAMAR",
        regCode:"08",
        provCode:"0848"
    },
    {
        id:23,
        name:"OCCIDENTAL MINDORO",
        regCode:"17",
        provCode:"1751"
    },
    {
        id:24,
        name:"ORIENTAL MINDORO",
        regCode:"17",
        provCode:"1752"
    },
    {
        id:25,
        name:"PALAWAN",
        regCode:"17",
        provCode:"1753"
    },
    {
        id:13,
        name:"PAMPANGA",
        regCode:"03",
        provCode:"0354"
    },
    {
        id:4,
        name:"PANGASINAN",
        regCode:"01",
        provCode:"0155"
    },
    {
        id:20,
        name:"QUEZON",
        regCode:"04",
        provCode:"0456"
    },
    {
        id:9,
        name:"QUIRINO",
        regCode:"02",
        provCode:"0257"
    },
    {
        id:21,
        name:"RIZAL",
        regCode:"04",
        provCode:"0458"
    },
    {
        id:26,
        name:"ROMBLON",
        regCode:"17",
        provCode:"1759"
    },
    {
        id:64,
        name:"SOUTH COTABATO",
        regCode:"12",
        provCode:"1263"
    },
    {
        id:65,
        name:"SULTAN KUDARAT",
        regCode:"12",
        provCode:"1265"
    },
    {
        id:66,
        name:"SARANGANI",
        regCode:"12",
        provCode:"1280"
    },
    {
        id:50,
        name:"SIQUIJOR",
        regCode:"07",
        provCode:"0761"
    },
    {
        id:46,
        name:"SOUTHERN LEYTE",
        regCode:"08",
        provCode:"0860"
    },
    {
        id:18,
        name:"SORSOGON",
        regCode:"05",
        provCode:"0562"
    },
    {
        id:77,
        name:"SURIGAO DEL NORTE",
        regCode:"16",
        provCode:"1667"
    },
    {
        id:83,
        name:"SURIGAO DEL SUR",
        regCode:"16",
        provCode:"1668"
    },
    {
        id:47,
        name:"SAMAR (WESTERN SAMAR)",
        regCode:"08",
        provCode:"0864"
    },
    {
        id:82,
        name:"SULU",
        regCode:"15",
        provCode:"1566"
    },
    {
        id:14,
        name:"TARLAC",
        regCode:"03",
        provCode:"0369"
    },
    {
        id:27,
        name:"TICAO",
        regCode:"05",
        provCode:"0527"
    },
    {
        id:15,
        name:"ZAMBALES",
        regCode:"03",
        provCode:"0372"
    },
    {
        id:56,
        name:"ZAMBOANGA DEL NORTE",
        regCode:"09",
        provCode:"0973"
    },
    {
        id:57,
        name:"ZAMBOANGA DEL SUR",
        regCode:"09",
        provCode:"0974"
    },
    {
        id:53,
        name:"ZAMBOANGA SIBUGAY",
        regCode:"09",
        provCode:"0983"
    }
];


export default provinces;
